// Customers
export const SET_CUSTOMERS_FETCHING_STATUS = 'SET_CUSTOMERS_FETCHING_STATUS';
export const SET_CUSTOMERS_FETCH_RESULT = 'SET_CUSTOMERS_FETCH_RESULT';
export const SET_CUSTOMERS_FILTERS = 'SET_CUSTOMER_FILTERS';

// Revenue
export const SET_CASHFLOW_FETCHING_STATUS = 'SET_CASHFLOW_FETCHING_STATUS';
export const SET_CASHFLOW_FETCH_RESULT = 'SET_CASHFLOW_FETCH_RESULT';
export const SET_CASHFLOW_FILTERS = 'SET_CASHFLOW_FILTERS';
